export const STORY_META = [
  { index: 1,  slug: 'the-last-census-of-zelkarun', title: 'The Last Census of Zelkarun',
    age: 'third', ageLabel: 'Third Age', year: 'Year 0 – 5 AI', sortYear: 0,
    regions: ['Verdure', 'Cinder'], places: ['Greymouth', 'the sea off Cinder', 'the Black Bastion'],
    engines: ['Tragedy', 'Adventure'],
    teaser: 'On the day the sky burns, a diplomat who resented her posting must learn what duty survives a civilization.',
    coverAlt: 'A white column of fire rising from a dark sea into a burning sky, ash over a small harbour.' },
  { index: 2,  slug: 'the-quiet-dial', title: 'The Quiet Dial',
    age: 'third', ageLabel: 'Third Age', year: '~195 BI', sortYear: -195,
    regions: ['Cinder'], places: ['Zelkarun', 'the Anchor works'],
    engines: ['Mystery', 'Tragedy'],
    teaser: 'Ordered to prove the throttled Anchor safe, an engineer\'s measurements say otherwise — and the report is already written.',
    coverAlt: 'A vast brass calibration dial in a dim engine hall, one needle trembling past its mark.' },
  { index: 3,  slug: 'the-long-dropped-stone', title: 'The Long-Dropped Stone',
    age: 'fifth', ageLabel: 'Fifth Age', year: '656 AI', sortYear: 656,
    regions: ['Verdure'], places: ['Aureon', 'the imperial archive'],
    engines: ['Mystery', 'Tragedy'],
    teaser: 'Why does a healthy second son renounce the greatest throne in history? One misfiled testament he cannot forget.',
    coverAlt: 'A single stone sinking through deep dark water, a thin shaft of light above it.' },
  { index: 4,  slug: 'the-empty-chair', title: 'The Empty Chair',
    age: 'fifth', ageLabel: 'Fifth Age', year: '874 AI', sortYear: 874,
    regions: ['Verdure'], places: ['Aureon'],
    engines: ['Tragedy'],
    teaser: 'The longest-reigning emperor is dead; the court waits for his daughter to sit. She weighs six centuries against one sentence.',
    coverAlt: 'An empty gilded throne in a vast hall, a shaft of pale light across the dais.' },
  { index: 5,  slug: 'five-rings', title: 'Five Rings',
    age: 'sixth', ageLabel: 'Sixth Age', year: '925 – 927 AI', sortYear: 925,
    regions: ['Verdure'], places: ['the ruins of Aureon'],
    engines: ['Adventure', 'Intrigue'],
    teaser: 'A girl who draws buildings nobody asked for and a dwarf far from his mountain scramble to found something new in a ruined capital.',
    coverAlt: 'Five signet rings on a rough-drawn architectural plan amid broken marble.' },
  { index: 6,  slug: 'the-mountain-that-sings', title: 'The Mountain That Sings',
    age: 'seventh', ageLabel: 'Seventh Age', year: '1140 AI', sortYear: 1140,
    regions: ['Sarudar'], places: ['Durumbar deeps'],
    engines: ['Mystery', 'Tragedy'],
    teaser: 'A new carving, a spire cracking in two, and a loremaster forced to choose between his oath and what the stone is plainly saying.',
    coverAlt: 'A cracked dwarven spire deep underground, faint resonance lines glowing in the stone.' },
  { index: 7,  slug: 'the-generals-ledger', title: 'The General\'s Ledger',
    age: 'seventh', ageLabel: 'Seventh Age', year: '1133 AI', sortYear: 1133,
    regions: ['Verdure'], places: ["Bastion's Reach"],
    engines: ['Mystery', 'Tragedy'],
    teaser: 'The youngest general exposes a duke and is destroyed by the proof — told from both sides of the palace wall.',
    coverAlt: 'A sealed packet and a ledger on a desk by candlelight behind a palace window.' },
  { index: 8,  slug: 'the-words-for-anchor-and-deep', title: 'The Words for Anchor and Deep',
    age: 'seventh', ageLabel: 'Seventh Age', year: '1141 AI', sortYear: 1141,
    regions: ['Cinder'], places: ['the Onyx Spires'],
    engines: ['Adventure', 'Mystery'],
    teaser: 'A thief climbs into the ash to prove her name and comes down carrying two words she can read and no one will hear.',
    coverAlt: 'A climber high on black glassy spires under an ash sky, a small stone tablet in hand.' },
  { index: 9,  slug: 'the-fourth-day-of-ambershade', title: 'The Fourth Day of Ambershade',
    age: 'seventh', ageLabel: 'Seventh Age', year: '1144 AI', sortYear: 1144,
    regions: ['Serene Sea'], places: ['Sea Breeze docks'],
    engines: ['Mystery', 'Melancholy'],
    teaser: 'The Honey Vigil comes as it has for three centuries — but since 1140 one gesture in the rite is different.',
    coverAlt: 'A lantern-lit dock at dusk, robed figures performing a sea rite, honey-gold light on still water.' },
  { index: 10, slug: 'moth-light', title: 'Moth-Light',
    age: 'seventh', ageLabel: 'Seventh Age', year: '1146 AI', sortYear: 1146,
    regions: ['Twiland'], places: ['Luneberg', 'the World Tree'],
    engines: ['Mystery', 'Romance'],
    teaser: 'A warden whose ledgers say the imprinted lives are shortening loves a Canopy Singer whose voice is failing the rites.',
    coverAlt: 'Pale moths circling a single lantern beneath the immense dark canopy of the World Tree.' },
  { index: 11, slug: 'the-door-below', title: 'The Door Below',
    age: 'seventh', ageLabel: 'Seventh Age', year: '1147 AI', sortYear: 1147,
    regions: ['Verdure'], places: ['Everpeak', 'the Hollows'],
    engines: ['Mystery', 'Intrigue'],
    teaser: 'An honest thief and a doubting inquisitor circle the same black-stone door in the Hollows — and neither can open it.',
    coverAlt: 'A great seamless black-stone door at the end of a wet river-tunnel, one lantern before it.' },
  { index: 12, slug: 'the-glimmer-vault', title: 'The Glimmer Vault',
    age: 'seventh', ageLabel: 'Seventh Age', year: '~1132 AI', sortYear: 1132,
    regions: ['Twiland'], places: ['Nilvelond'],
    engines: ['Romance', 'Intrigue'],
    teaser: 'A half-elf clerk and a bloodline vault-warden fall in love across a counter of other people\'s treasure — until the law gives her a reason to rob it.',
    coverAlt: 'A jewelled vault interior glittering with Glimmers, two figures at a counter in warm dim light.' },
]
